const ShopData = [
  {
    id: "boots",
    title: "boots",
    backgroundImgURL: "https://i.ibb.co/mSNpN1w/boots.jpg",
    description:
      "Find the latest unisex boots and ankle boots from Muroexe. Comfortable, flexible and high quality vegan footwear that always fits the shape of your feet.",
    pathUrl: "/shop/boots",
    items: [
      {
        id: 1,
        name: "Atom Ochre Boot",
        description:
          "With Alpha Boot we wanted to reinvent the classic trekking boot but with a much lighter, urban and comfortable sole. All this is due to the implementation of our latest sole: Alpha, with which we have achieved optimal grip, no matter the situation. In addition, thanks to its waxed microfiber surface, PU and its internal mesh lining, it makes it perfect for winter and the inclemency of your day to day in the city. The future of trekking boots is here.",
        imageUrl: "https://i.ibb.co/3hs1ZC9/alpha-boot-black.jpg",
        hoverImgUrl: "https://i.ibb.co/5RcVrrr/alpha-boot-black-HV.jpg",
        price: 120,
        onSaleValue: 20,
        size: ["36", "40", "42", "48"],
        style: "formal",
        newState: true,
      },
      {
        id: 2,
        name: "Alpha Boot Brown",
        description:
          "With Alpha Boot we wanted to reinvent the classic trekking boot but with a much lighter, urban and comfortable sole. All this is due to the implementation of our latest sole: Alpha, with which we have achieved optimal grip, no matter the situation. In addition, thanks to its waxed microfiber surface, PU and its internal mesh lining, it makes it perfect for winter and the inclemency of your day to day in the city. The future of trekking boots is here.",
        imageUrl: "https://i.ibb.co/C5H64jd/alpha-boot-brown.jpg",
        hoverImgUrl: "https://i.ibb.co/bb7LXwK/alpha-boot-brown-HV.jpg",
        price: 100,
        size: ["36", "40", "42", "48"],
        style: "casual",
      },
      {
        id: 3,
        name: "Alpha Boot Black",
        description:
          "With Alpha Boot we wanted to reinvent the classic trekking boot but with a much lighter, urban and comfortable sole. All this is due to the implementation of our latest sole: Alpha, with which we have achieved optimal grip, no matter the situation. In addition, thanks to its waxed microfiber surface, PU and its internal mesh lining, it makes it perfect for winter and the inclemency of your day to day in the city. The future of trekking boots is here.",
        imageUrl: "https://i.ibb.co/c8q2Z3B/army-boot-black.jpg",
        hoverImgUrl: "https://i.ibb.co/fV32qLW/army-boot-black-HV.jpg",
        price: 145,
        onSaleValue: 50,
        size: ["36", "40", "42", "48"],
        style: "classic",
      },
      {
        id: 4,
        name: "Army Boot Black",
        description:
          "With Alpha Boot we wanted to reinvent the classic trekking boot but with a much lighter, urban and comfortable sole. All this is due to the implementation of our latest sole: Alpha, with which we have achieved optimal grip, no matter the situation. In addition, thanks to its waxed microfiber surface, PU and its internal mesh lining, it makes it perfect for winter and the inclemency of your day to day in the city. The future of trekking boots is here.",
        imageUrl: "https://i.ibb.co/sHtvHZP/army-boot-blue.jpg",
        hoverImgUrl: "https://i.ibb.co/2v9xQQp/army-boot-blue-HV.jpg",
        price: 78,
        onSaleValue: 15,
        size: ["36", "40", "42", "48"],
        style: "classic",
        newState: true,
      },
      {
        id: 5,
        name: "Ucon Black",
        description:
          "With Alpha Boot we wanted to reinvent the classic trekking boot but with a much lighter, urban and comfortable sole. All this is due to the implementation of our latest sole: Alpha, with which we have achieved optimal grip, no matter the situation. In addition, thanks to its waxed microfiber surface, PU and its internal mesh lining, it makes it perfect for winter and the inclemency of your day to day in the city. The future of trekking boots is here.",
        imageUrl: "https://i.ibb.co/n0fNHNf/army-boot-ochre.jpg",
        hoverImgUrl: "https://i.ibb.co/Kjyjfxy/army-boot-ochre-HV.jpg",
        price: 130,
        onSaleValue: 45,
        size: ["36", "40", "42", "48"],
        style: "Smart and Formal",
      },
      {
        id: 6,
        name: "Atom Black Boot",
        description:
          "With Alpha Boot we wanted to reinvent the classic trekking boot but with a much lighter, urban and comfortable sole. All this is due to the implementation of our latest sole: Alpha, with which we have achieved optimal grip, no matter the situation. In addition, thanks to its waxed microfiber surface, PU and its internal mesh lining, it makes it perfect for winter and the inclemency of your day to day in the city. The future of trekking boots is here.",
        imageUrl: "https://i.ibb.co/4Zwk1rg/atom-brown-boot.jpg",
        hoverImgUrl: "https://i.ibb.co/RB9bhZn/atom-brown-boot-HV.jpg",
        price: 65,
        size: ["36", "40", "42", "48"],
        style: "casual",
      },
      {
        id: 7,
        name: "Army Boot Blue",
        description:
          "With Alpha Boot we wanted to reinvent the classic trekking boot but with a much lighter, urban and comfortable sole. All this is due to the implementation of our latest sole: Alpha, with which we have achieved optimal grip, no matter the situation. In addition, thanks to its waxed microfiber surface, PU and its internal mesh lining, it makes it perfect for winter and the inclemency of your day to day in the city. The future of trekking boots is here.",
        imageUrl: "https://i.ibb.co/85WQ8qK/atom-grey-boot.jpg",
        hoverImgUrl: "https://i.ibb.co/FH8Pj6b/atom-grey-boot-HV.jpg",
        price: 85,
        onSaleValue: 10,
        size: ["36", "40", "42", "48"],
        style: "SmartandFormal",
      },
      {
        id: 8,
        name: "Atom Gray Boot",
        description:
          "With Alpha Boot we wanted to reinvent the classic trekking boot but with a much lighter, urban and comfortable sole. All this is due to the implementation of our latest sole: Alpha, with which we have achieved optimal grip, no matter the situation. In addition, thanks to its waxed microfiber surface, PU and its internal mesh lining, it makes it perfect for winter and the inclemency of your day to day in the city. The future of trekking boots is here.",
        imageUrl: "https://i.ibb.co/nrkjbJv/atom-mist-beige.jpg",
        hoverImgUrl: "https://i.ibb.co/HCZN875/atom-mist-beige-HV.jpg",
        price: 89,
        size: ["36", "40", "42", "48"],
        style: "casual",
      },
      {
        id: 9,
        name: "Alpha Army Boot ",
        description:
          "With Alpha Boot we wanted to reinvent the classic trekking boot but with a much lighter, urban and comfortable sole. All this is due to the implementation of our latest sole: Alpha, with which we have achieved optimal grip, no matter the situation. In addition, thanks to its waxed microfiber surface, PU and its internal mesh lining, it makes it perfect for winter and the inclemency of your day to day in the city. The future of trekking boots is here.",
        imageUrl: "https://i.ibb.co/kHrFBzh/atom-ochre-boot.jpg",
        hoverImgUrl: "https://i.ibb.co/Csy6S2y/atom-ochre-boot-HV.jpg",
        price: 157,
        size: ["36", "40", "42", "48"],
        style: "Smart and Formal",
      },
      {
        id: 10,
        name: "Atom Mist Blue",
        description:
          "With Alpha Boot we wanted to reinvent the classic trekking boot but with a much lighter, urban and comfortable sole. All this is due to the implementation of our latest sole: Alpha, with which we have achieved optimal grip, no matter the situation. In addition, thanks to its waxed microfiber surface, PU and its internal mesh lining, it makes it perfect for winter and the inclemency of your day to day in the city. The future of trekking boots is here.",
        imageUrl: "https://i.ibb.co/NYDjx8X/meteor-black-1.jpg",
        hoverImgUrl: "https://i.ibb.co/zxSQNHw/atom-mist-vintage-black-HV.png",
        price: 200,
        onSaleValue: 20,
        size: ["36", "40", "42", "48"],
        style: "Smart and Formal",
      },
      {
        id: 11,
        name: "Atom Mist Gray",
        description:
          "With Alpha Boot we wanted to reinvent the classic trekking boot but with a much lighter, urban and comfortable sole. All this is due to the implementation of our latest sole: Alpha, with which we have achieved optimal grip, no matter the situation. In addition, thanks to its waxed microfiber surface, PU and its internal mesh lining, it makes it perfect for winter and the inclemency of your day to day in the city. The future of trekking boots is here.",
        imageUrl: "https://i.ibb.co/YZfLnc2/meteor-blue.jpg",
        hoverImgUrl: "https://i.ibb.co/9hV32pd/atom-mist-vintage-blue-HV.png",
        price: 100,
        size: ["36", "40", "42", "48"],
        style: "Smart and Formal",
        newState: true,
      },
      {
        id: 12,
        name: "Marathon Black Boot",
        description:
          "With Alpha Boot we wanted to reinvent the classic trekking boot but with a much lighter, urban and comfortable sole. All this is due to the implementation of our latest sole: Alpha, with which we have achieved optimal grip, no matter the situation. In addition, thanks to its waxed microfiber surface, PU and its internal mesh lining, it makes it perfect for winter and the inclemency of your day to day in the city. The future of trekking boots is here.",
        imageUrl: "https://i.ibb.co/nrkjbJv/atom-mist-beige.jpg",
        hoverImgUrl: "https://i.ibb.co/rF79Cr4/atom-mist-grey-HV.jpg",
        price: 126,
        size: ["36", "40", "42", "48"],
        style: "casual",
      },
    ],
  },
  {
    id: "sneakers",
    title: "sneakers",
    backgroundImgURL: "https://i.ibb.co/1MSvhcZ/sneakers.jpg",
    description:
      "Discover the Muroexe sneakers collection on our website. Vegan sneakers at the best price and with a wide range of models available. Maximum comfort and flexibility.",
    pathUrl: "/shop/sneakers",
    items: [
      {
        id: 13,
        name: "alaska grey",
        description:
          "With Alpha Boot we wanted to reinvent the classic trekking boot but with a much lighter, urban and comfortable sole. All this is due to the implementation of our latest sole: Alpha, with which we have achieved optimal grip, no matter the situation. In addition, thanks to its waxed microfiber surface, PU and its internal mesh lining, it makes it perfect for winter and the inclemency of your day to day in the city. The future of trekking boots is here.",
        imageUrl: "https://i.ibb.co/syCVgMk/alaska-grey.jpg",
        hoverImgUrl: "https://i.ibb.co/j8BKV5F/alaska-grey-HV.jpg",
        price: 111,
        onSaleValue: 20,
        size: ["36", "40", "42", "48"],
        style: "formal",
      },
      {
        id: 14,
        name: "alpha carbono dark red",
        description:
          "With Alpha Boot we wanted to reinvent the classic trekking boot but with a much lighter, urban and comfortable sole. All this is due to the implementation of our latest sole: Alpha, with which we have achieved optimal grip, no matter the situation. In addition, thanks to its waxed microfiber surface, PU and its internal mesh lining, it makes it perfect for winter and the inclemency of your day to day in the city. The future of trekking boots is here.",
        imageUrl: "https://i.ibb.co/QpyjB5b/alpha-carbono-dark-red.jpg",
        hoverImgUrl: "https://i.ibb.co/1vrG7Yd/alpha-carbono-dark-red-HV.jpg",
        price: 150,
        onSaleValue: 20,
        size: ["36", "40", "42", "48"],
        style: "formal",
      },
      {
        id: 15,
        name: "alpha neo beige",
        description:
          "With Alpha Boot we wanted to reinvent the classic trekking boot but with a much lighter, urban and comfortable sole. All this is due to the implementation of our latest sole: Alpha, with which we have achieved optimal grip, no matter the situation. In addition, thanks to its waxed microfiber surface, PU and its internal mesh lining, it makes it perfect for winter and the inclemency of your day to day in the city. The future of trekking boots is here.",
        imageUrl: "https://i.ibb.co/JrFnQXm/alpha-neo-beige.png",
        hoverImgUrl: "https://i.ibb.co/YBW9TG5/alpha-neo-beige-HV.png",
        price: 76,
        size: ["36", "40", "42", "48"],
        style: "formal",
        newState: true,
      },
      {
        id: 16,
        name: "alpha neo dark grey",
        description:
          "With Alpha Boot we wanted to reinvent the classic trekking boot but with a much lighter, urban and comfortable sole. All this is due to the implementation of our latest sole: Alpha, with which we have achieved optimal grip, no matter the situation. In addition, thanks to its waxed microfiber surface, PU and its internal mesh lining, it makes it perfect for winter and the inclemency of your day to day in the city. The future of trekking boots is here.",
        imageUrl: "https://i.ibb.co/nPTR26h/alpha-neo-dark-grey.png",
        hoverImgUrl: "https://i.ibb.co/5vNJ2y1/alpha-neo-dark-grey-HV.png",
        price: 93,
        onSaleValue: 35,
        size: ["36", "40", "42", "48"],
        style: "formal",
      },
      {
        id: 17,
        name: "alpha neo pink",
        description:
          "With Alpha Boot we wanted to reinvent the classic trekking boot but with a much lighter, urban and comfortable sole. All this is due to the implementation of our latest sole: Alpha, with which we have achieved optimal grip, no matter the situation. In addition, thanks to its waxed microfiber surface, PU and its internal mesh lining, it makes it perfect for winter and the inclemency of your day to day in the city. The future of trekking boots is here.",
        imageUrl: "https://i.ibb.co/bs4xktd/alpha-neo-pink.jpg",
        hoverImgUrl: "https://i.ibb.co/VjBT9M3/alpha-neo-pink-HV.png",
        price: 85,
        onSaleValue: 20,
        size: ["36", "40", "42", "48"],
        style: "formal",
      },
      {
        id: 18,
        name: "army blue",
        description:
          "With Alpha Boot we wanted to reinvent the classic trekking boot but with a much lighter, urban and comfortable sole. All this is due to the implementation of our latest sole: Alpha, with which we have achieved optimal grip, no matter the situation. In addition, thanks to its waxed microfiber surface, PU and its internal mesh lining, it makes it perfect for winter and the inclemency of your day to day in the city. The future of trekking boots is here.",
        imageUrl: "https://i.ibb.co/Gxz7JWC/army-blue.jpg",
        hoverImgUrl: "https://i.ibb.co/4dgWh2t/army-blue-HV.jpg",
        price: 99,
        size: ["36", "40", "42", "48"],
        style: "formal",
      },
      {
        id: 19,
        name: "army grey",
        description:
          "With Alpha Boot we wanted to reinvent the classic trekking boot but with a much lighter, urban and comfortable sole. All this is due to the implementation of our latest sole: Alpha, with which we have achieved optimal grip, no matter the situation. In addition, thanks to its waxed microfiber surface, PU and its internal mesh lining, it makes it perfect for winter and the inclemency of your day to day in the city. The future of trekking boots is here.",
        imageUrl: "https://i.ibb.co/Ln7V3Cn/army-grey.jpg",
        hoverImgUrl: "https://i.ibb.co/PQJXCRw/army-grey-HV.jpg",
        price: 147,
        size: ["36", "40", "42", "48"],
        style: "formal",
      },
      {
        id: 20,
        name: "atom oasis orange",
        description:
          "With Alpha Boot we wanted to reinvent the classic trekking boot but with a much lighter, urban and comfortable sole. All this is due to the implementation of our latest sole: Alpha, with which we have achieved optimal grip, no matter the situation. In addition, thanks to its waxed microfiber surface, PU and its internal mesh lining, it makes it perfect for winter and the inclemency of your day to day in the city. The future of trekking boots is here.",
        imageUrl: "https://i.ibb.co/Xt9Rt62/atom-oasis-orange.png",
        hoverImgUrl: "https://i.ibb.co/PTYc5Hw/atom-oasis-orange-HV.png",
        price: 168,
        size: ["36", "40", "42", "48"],
        style: "formal",
        newState: true,
      },
      {
        id: 21,
        name: "atom oasis red",
        description:
          "With Alpha Boot we wanted to reinvent the classic trekking boot but with a much lighter, urban and comfortable sole. All this is due to the implementation of our latest sole: Alpha, with which we have achieved optimal grip, no matter the situation. In addition, thanks to its waxed microfiber surface, PU and its internal mesh lining, it makes it perfect for winter and the inclemency of your day to day in the city. The future of trekking boots is here.",
        imageUrl: "https://i.ibb.co/Xx8QRkw/atom-oasis-red.png",
        hoverImgUrl: "https://i.ibb.co/8gWqWpM/atom-oasis-red-HV.png",
        price: 89,
        onSaleValue: 11,
        size: ["36", "40", "42", "48"],
        style: "formal",
      },
      {
        id: 22,
        name: "density blue",
        description:
          "With Alpha Boot we wanted to reinvent the classic trekking boot but with a much lighter, urban and comfortable sole. All this is due to the implementation of our latest sole: Alpha, with which we have achieved optimal grip, no matter the situation. In addition, thanks to its waxed microfiber surface, PU and its internal mesh lining, it makes it perfect for winter and the inclemency of your day to day in the city. The future of trekking boots is here.",
        imageUrl: "https://i.ibb.co/n0mtb3r/density-blue.jpg",
        hoverImgUrl: "https://i.ibb.co/s2Yh1nd/density-blue-HV.jpg",
        price: 100,
        onSaleValue: 70,
        size: ["36", "40", "42", "48"],
        style: "formal",
      },
      {
        id: 23,
        name: "hybrid black",
        description:
          "With Alpha Boot we wanted to reinvent the classic trekking boot but with a much lighter, urban and comfortable sole. All this is due to the implementation of our latest sole: Alpha, with which we have achieved optimal grip, no matter the situation. In addition, thanks to its waxed microfiber surface, PU and its internal mesh lining, it makes it perfect for winter and the inclemency of your day to day in the city. The future of trekking boots is here.",
        imageUrl: "https://i.ibb.co/YPS8pHj/hybrid-black.jpg",
        hoverImgUrl: "https://i.ibb.co/Zg1Wkzs/hybrid-black-HV.jpg",
        price: 42,
        size: ["36", "40", "42", "48"],
        style: "formal",
      },
      {
        id: 24,
        name: "juno cloud blue",
        description:
          "With Alpha Boot we wanted to reinvent the classic trekking boot but with a much lighter, urban and comfortable sole. All this is due to the implementation of our latest sole: Alpha, with which we have achieved optimal grip, no matter the situation. In addition, thanks to its waxed microfiber surface, PU and its internal mesh lining, it makes it perfect for winter and the inclemency of your day to day in the city. The future of trekking boots is here.",
        imageUrl: "https://i.ibb.co/NY37gZd/juno-cloud-blue.jpg",
        hoverImgUrl: "https://i.ibb.co/f9CT5YJ/juno-cloud-blue-HV.jpg",
        price: 96,
        size: ["36", "40", "42", "48"],
        style: "formal",
        newState: true,
      },
    ],
  },
  {
    id: "slippers",
    title: "slippers",
    backgroundImgURL: "https://i.ibb.co/12y79Tx/slippers.jpg",
    description:
      "Enjoy the comfort of Muroexe slippers. Ecological slippers for women and men with great comfort and flexibility.",
    pathUrl: "/shop/slippers",
    items: [
      {
        id: 25,
        name: "home mood black",
        description:
          "With Alpha Boot we wanted to reinvent the classic trekking boot but with a much lighter, urban and comfortable sole. All this is due to the implementation of our latest sole: Alpha, with which we have achieved optimal grip, no matter the situation. In addition, thanks to its waxed microfiber surface, PU and its internal mesh lining, it makes it perfect for winter and the inclemency of your day to day in the city. The future of trekking boots is here.",
        imageUrl: "https://i.ibb.co/M2JDL6M/home-mood-black.png",
        hoverImgUrl: "https://i.ibb.co/YDZfLbn/home-mood-black-HV.png",
        price: 120,
        onSaleValue: 20,
        size: ["36", "40", "42", "48"],
        style: "formal",
      },
      {
        id: 26,
        name: "home mood blue",
        description:
          "With Alpha Boot we wanted to reinvent the classic trekking boot but with a much lighter, urban and comfortable sole. All this is due to the implementation of our latest sole: Alpha, with which we have achieved optimal grip, no matter the situation. In addition, thanks to its waxed microfiber surface, PU and its internal mesh lining, it makes it perfect for winter and the inclemency of your day to day in the city. The future of trekking boots is here.",
        imageUrl: "https://i.ibb.co/8dRm9qp/home-mood-blue.png",
        hoverImgUrl: "https://i.ibb.co/BsWb6tg/home-mood-blue-HV.png",
        price: 100,
        size: ["36", "40", "42", "48"],
        style: "casual",
        newState: true,
      },
      {
        id: 27,
        name: "slipper grey",
        description:
          "With Alpha Boot we wanted to reinvent the classic trekking boot but with a much lighter, urban and comfortable sole. All this is due to the implementation of our latest sole: Alpha, with which we have achieved optimal grip, no matter the situation. In addition, thanks to its waxed microfiber surface, PU and its internal mesh lining, it makes it perfect for winter and the inclemency of your day to day in the city. The future of trekking boots is here.",
        imageUrl: "https://i.ibb.co/W28M1rK/slipper-grey.jpg",
        hoverImgUrl: "https://i.ibb.co/zbDWMwR/slipper-grey-HV.jpg",
        price: 145,
        onSaleValue: 50,
        size: ["36", "40", "42", "48"],
        style: "classic",
      },
    ],
  },
  {
    id: "accessories",
    title: "accessories",
    backgroundImgURL: "https://i.ibb.co/pj8qCBQ/accessories.jpg",
    description:
      "Discover the Muroexe accessories collection on our website. Accessories, bags, backpacks, wallets and much more! Unisex and 100% cruelty free.",
    pathUrl: "/shop/accessories",
    items: [
      {
        id: 28,
        name: "Block Beige",
        description:
          "With Alpha Boot we wanted to reinvent the classic trekking boot but with a much lighter, urban and comfortable sole. All this is due to the implementation of our latest sole: Alpha, with which we have achieved optimal grip, no matter the situation. In addition, thanks to its waxed microfiber surface, PU and its internal mesh lining, it makes it perfect for winter and the inclemency of your day to day in the city. The future of trekking boots is here.",
        imageUrl: "https://i.ibb.co/PZCYprP/block-beige.jpg",
        hoverImgUrl: "https://i.ibb.co/qYst91H/block-beige-HV.jpg",
        price: 45,
        onSaleValue: 10,
        size: ["36", "40", "42", "48"],
        style: "formal",
        newState: true,
      },
      {
        id: 29,
        name: "Block Black",
        description:
          "With Alpha Boot we wanted to reinvent the classic trekking boot but with a much lighter, urban and comfortable sole. All this is due to the implementation of our latest sole: Alpha, with which we have achieved optimal grip, no matter the situation. In addition, thanks to its waxed microfiber surface, PU and its internal mesh lining, it makes it perfect for winter and the inclemency of your day to day in the city. The future of trekking boots is here.",
        imageUrl: "https://i.ibb.co/W2GQbfT/block-black.jpg",
        hoverImgUrl: "https://i.ibb.co/mSHdgC4/block-black-HV.jpg",
        price: 78,
        onSaleValue: 20,
        size: ["36", "40", "42", "48"],
        style: "formal",
      },
      {
        id: 30,
        name: "Block Blue",
        description:
          "With Alpha Boot we wanted to reinvent the classic trekking boot but with a much lighter, urban and comfortable sole. All this is due to the implementation of our latest sole: Alpha, with which we have achieved optimal grip, no matter the situation. In addition, thanks to its waxed microfiber surface, PU and its internal mesh lining, it makes it perfect for winter and the inclemency of your day to day in the city. The future of trekking boots is here.",
        imageUrl: "https://i.ibb.co/48CxTX8/block-blue.jpg",
        hoverImgUrl: "https://i.ibb.co/mv1bB7V/block-blue-HV.jpg",
        price: 111,
        size: ["36", "40", "42", "48"],
        style: "formal",
        newState: true,
      },
      {
        id: 31,
        name: "Camisa Neta",
        description:
          "With Alpha Boot we wanted to reinvent the classic trekking boot but with a much lighter, urban and comfortable sole. All this is due to the implementation of our latest sole: Alpha, with which we have achieved optimal grip, no matter the situation. In addition, thanks to its waxed microfiber surface, PU and its internal mesh lining, it makes it perfect for winter and the inclemency of your day to day in the city. The future of trekking boots is here.",
        imageUrl: "https://i.ibb.co/bJBY1kc/camisa-neta.jpg",
        hoverImgUrl: "https://i.ibb.co/JmbWpx9/camisa-neta-HV.jpg",
        price: 120,
        onSaleValue: 10,
        size: ["36", "40", "42", "48"],
        style: "formal",
      },
      {
        id: 32,
        name: "Cordones Eternal Grape",
        description:
          "With Alpha Boot we wanted to reinvent the classic trekking boot but with a much lighter, urban and comfortable sole. All this is due to the implementation of our latest sole: Alpha, with which we have achieved optimal grip, no matter the situation. In addition, thanks to its waxed microfiber surface, PU and its internal mesh lining, it makes it perfect for winter and the inclemency of your day to day in the city. The future of trekking boots is here.",
        imageUrl: "https://i.ibb.co/GxLMHGD/cordones-eternal-grape.jpg",
        hoverImgUrl: "https://i.ibb.co/BqdcmwG/cordones-eternal-grape-HV.jpg",
        price: 78,
        onSaleValue: 12,
        size: ["36", "40", "42", "48"],
        style: "formal",
      },
      {
        id: 33,
        name: "Cordones jaspeado negro",
        description:
          "With Alpha Boot we wanted to reinvent the classic trekking boot but with a much lighter, urban and comfortable sole. All this is due to the implementation of our latest sole: Alpha, with which we have achieved optimal grip, no matter the situation. In addition, thanks to its waxed microfiber surface, PU and its internal mesh lining, it makes it perfect for winter and the inclemency of your day to day in the city. The future of trekking boots is here.",
        imageUrl: "https://i.ibb.co/pJHvsT5/cordones-jaspeado-negro.jpg",
        hoverImgUrl: "https://i.ibb.co/HVy4JVf/cordones-jaspeado-negro-HV.jpg",
        price: 45,
        size: ["36", "40", "42", "48"],
        style: "formal",
      },
      {
        id: 34,
        name: "The pocket Beige (Zipper)",
        description:
          "With Alpha Boot we wanted to reinvent the classic trekking boot but with a much lighter, urban and comfortable sole. All this is due to the implementation of our latest sole: Alpha, with which we have achieved optimal grip, no matter the situation. In addition, thanks to its waxed microfiber surface, PU and its internal mesh lining, it makes it perfect for winter and the inclemency of your day to day in the city. The future of trekking boots is here.",
        imageUrl: "https://i.ibb.co/jbjfc2y/pocket-x-beige.jpg",
        hoverImgUrl: "https://i.ibb.co/jvYxQvx/pocket-x-beige-HV.jpg",
        price: 48,
        size: ["36", "40", "42", "48"],
        style: "formal",
        newState: true,
      },
      {
        id: 35,
        name: "The pocket Black (Zipper)",
        description:
          "With Alpha Boot we wanted to reinvent the classic trekking boot but with a much lighter, urban and comfortable sole. All this is due to the implementation of our latest sole: Alpha, with which we have achieved optimal grip, no matter the situation. In addition, thanks to its waxed microfiber surface, PU and its internal mesh lining, it makes it perfect for winter and the inclemency of your day to day in the city. The future of trekking boots is here.",
        imageUrl: "https://i.ibb.co/MM5B67D/pocket-x-black.jpg",
        hoverImgUrl: "https://i.ibb.co/XxbV1M2/pocket-x-black-HV.jpg",
        price: 78,
        size: ["36", "40", "42", "48"],
        style: "formal",
      },
      {
        id: 36,
        name: "The pocket Black",
        description:
          "With Alpha Boot we wanted to reinvent the classic trekking boot but with a much lighter, urban and comfortable sole. All this is due to the implementation of our latest sole: Alpha, with which we have achieved optimal grip, no matter the situation. In addition, thanks to its waxed microfiber surface, PU and its internal mesh lining, it makes it perfect for winter and the inclemency of your day to day in the city. The future of trekking boots is here.",
        imageUrl: "https://i.ibb.co/qCmsDb6/pocket-y-black.jpg",
        hoverImgUrl: "https://i.ibb.co/sVThMG0/pocket-y-black-HV.jpg",
        price: 90,
        onSaleValue: 10,
        size: ["36", "40", "42", "48"],
        style: "formal",
        newState: true,
      },
      {
        id: 37,
        name: "The pocket Blue",
        description:
          "With Alpha Boot we wanted to reinvent the classic trekking boot but with a much lighter, urban and comfortable sole. All this is due to the implementation of our latest sole: Alpha, with which we have achieved optimal grip, no matter the situation. In addition, thanks to its waxed microfiber surface, PU and its internal mesh lining, it makes it perfect for winter and the inclemency of your day to day in the city. The future of trekking boots is here.",
        imageUrl: "https://i.ibb.co/bXWLrGj/pocket-y-blue.jpg",
        hoverImgUrl: "https://i.ibb.co/SnKZ50j/pocket-y-blue-HV.jpg",
        price: 100,
        size: ["36", "40", "42", "48"],
        style: "formal",
      },
      {
        id: 38,
        name: "Suite Blue",
        description:
          "With Alpha Boot we wanted to reinvent the classic trekking boot but with a much lighter, urban and comfortable sole. All this is due to the implementation of our latest sole: Alpha, with which we have achieved optimal grip, no matter the situation. In addition, thanks to its waxed microfiber surface, PU and its internal mesh lining, it makes it perfect for winter and the inclemency of your day to day in the city. The future of trekking boots is here.",
        imageUrl: "https://i.ibb.co/HzQxnHF/suite-blue.jpg",
        hoverImgUrl: "https://i.ibb.co/3h18jtB/suite-blue-HV.jpg",
        price: 20,
        onSaleValue: 15,
        size: ["36", "40", "42", "48"],
        style: "formal",
      },
      {
        id: 39,
        name: "Suite Grape",
        description:
          "With Alpha Boot we wanted to reinvent the classic trekking boot but with a much lighter, urban and comfortable sole. All this is due to the implementation of our latest sole: Alpha, with which we have achieved optimal grip, no matter the situation. In addition, thanks to its waxed microfiber surface, PU and its internal mesh lining, it makes it perfect for winter and the inclemency of your day to day in the city. The future of trekking boots is here.",
        imageUrl: "https://i.ibb.co/K5T67yg/suite-grape.jpg",
        hoverImgUrl: "https://i.ibb.co/120RmWD/suite-grape-HV.jpg",
        price: 74,
        onSaleValue: 35,
        size: ["36", "40", "42", "48"],
        style: "formal",
      },
    ],
  },
];
export default ShopData;
